name: "PR checks - Tests"

on:
  pull_request:
    branches:
      - main

jobs:
  acceptance-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Wait for push
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: push-images
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 5
      
      - name: Acceptance Tests
        run: |
          echo "Running Acceptance tests..."
          sleep 5
          echo "Done"
